app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_jwt_extended import (create_access_token,
                                create_refresh_token,
                                jwt_required,
                                set_access_cookies,
                                unset_jwt_cookies)
import datetime
from flask import jsonify
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_jwt_extended import JWTManager
from . import db

class Patient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(64))
    lastname = db.Column(db.String(64))
    date_of_birth = db.Column(db.String(64))
    sex = db.Column(db.String(64))
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    image_id = db.Column(db.Integer)
    status = db.Column(db.String(64))

    def populate_obj(obj):
        super().populate_obj(obj)


class Acquisition(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    eye = db.Column(db.String(64))
    site_name = db.Column(db.String(64))
    date_taken = db.Column(db.String(64))
    operator_name = db.Column(db.String(64))
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    image_data = db.Column(db.LargeBinary)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo

class PatientForm(FlaskForm):
    firstname = StringField('Firstname', validators=[DataRequired()])
    lastname = StringField('Lastname', validators=[DataRequired()])
    date_of_birth = StringField('Date of Birth', validators=[DataRequired()])
    sex = StringField('Sex', validators=[DataRequired()])
    submit = SubmitField('Create new Patient')

class UpdatePatientForm(FlaskForm):
    firstname = StringField('Firstname', validators=[DataRequired()])
    lastname = StringField('Lastname', validators=[DataRequired()])
    date_of_birth = StringField('Date of Birth', validators=[DataRequired()])
    sex = StringField('Sex', validators=[DataRequired()])
    submit = SubmitField('Update Patient')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_cors import CORS
from flask_bootstrap import Bootstrap
import os

def create_app(config_filename):
    app = Flask(__name__)
    bootstrap = Bootstrap(app)
    app.config.from_object(config_filename)

    CORS(app)

    from .models import db, migrate, jwt
    db.init_app(app)
    migrate.init_app(app, db)
    jwt.init_app(app)

    from .blueprints.patient_blueprint import patient_blueprint, acquisition_blueprint
    app.register_blueprint(patient_blueprint)
    app.register_blueprint(acquisition_blueprint)

    return app

app = create_app(Config)

app/blueprints/acquisition_blueprint.py
from flask import Blueprint, make_response, render_template, redirect, url_for, request
from ..forms import PatientForm, UpdatePatientForm
from ..models import Patient
from random import randint
from ..models import db 
acquisition_blueprint = Blueprint('acquisition_blueprint', __name__)

@acquisition_blueprint.route("/acquisitions")
def acquisitions():
    pass


class CardinalContainer(Container):

app/blueprints/patient_blueprint.py
from flask import Blueprint, make_response, render_template, redirect, url_for, request
from ..forms import PatientForm, UpdatePatientForm
from ..models import Patient
from random import randint
from ..models import db 
patient_blueprint = Blueprint('patient_blueprint', __name__)

new.route("/")
def index():
    return redirect(url_for('patient_blueprint.patients'))

new.route("/patients", methods=["GET"])
def patients():
    patients = Patient.query.all()
    return render_template('patients.html', patients = patients)

new.route("/patients/new", methods=["GET", "POST"])
def form_create_patient():
    if request.method == "POST":
        req = request.form
        new_patient = Patient(firstname = req["firstname"],
                                    lastname = req["lastname"],
                                    date_of_birth = req["date_of_birth"],
                                    sex = req["sex"],
                                    image_id = randint(1, 90),
                                    status = "New")
        db.session.add(new_patient)
        db.session.commit()
        return redirect(url_for('patient_blueprint.patients'))
    form = PatientForm()
    return render_template('new_patient_form.html', form=form)

new.route("/patients/:id", methods=["GET"])
def get_patient(id):
    pass

new.route("/patients/<id>", methods=["GET"])
def delete_patient(id):
    patient = Patient.query.get(id)
    db.session.delete(patient)
    db.session.commit()
    return redirect(url_for('patient_blueprint.patients'))

new.route("/update_patients/<id>", methods=["GET", "POST"])
def update_patient(id):
    patient = Patient.query.get(id)
    if request.method == "POST":
        req = request.form
        print(req)
        patient.firstname = req["firstname"]
        patient.lastname = req["lastname"]
        patient.date_of_birth = req["date_of_birth"]
        patient.sex = req["sex"]
        db.session.commit()
        return redirect(url_for('patient_blueprint.patients'))

    form = UpdatePatientForm(obj=patient)
    return render_template('new_patient_form.html', form=form)

app/routes.py
from app import app, db, jwt
from flask_jwt_extended import get_jwt
from config import Config


from flask import render_template, redirect, flash, url_for, request, session, jsonify, make_response
from flask_login import current_user, login_user, logout_user, login_required
from flask_jwt_extended import jwt_required
from flask_jwt_extended import get_jwt_identity

from werkzeug.security import generate_password_hash, check_password_hash

@app.route('/')
def index():
    print("hello")
    return 'hello world'

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Retispec</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<nav class="bg-gray-300 border-gray-200 px-2 sm:px-4 py-2.5 rounded">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="https://retispec.com/" class="flex items-center">
        <img src="https://static.wixstatic.com/media/efca5f_c58586be74a34a82ad83390ebf915242~mv2.png/v1/fill/w_207,h_52,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/RetiSpec_Logo%200721-02.png" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo" />
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white">
        <li>
            <a href="{{ url_for('patient_blueprint.patients') }}" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-900 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400">Patients</a>
        </li>
        <li>
          <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-900 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400">Acquisitions</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/new_patient_form.html
{% include 'navbar.html' %}
<div class="min-w-screen min-h-screen bg-gray-100 flex justify-center bg-gray-100 font-sans overflow-hidden mb-12">
  {% extends "bootstrap/base.html" %}
  {% import "bootstrap/wtf.html" as wtf %}
  {% block content %}
  {{ wtf.quick_form(form) }}
  {%endblock%}
</div>

app/templates/patients.html
{% include 'navbar.html' %}
<div class="overflow-x-auto">
  <div class="min-w-screen min-h-screen bg-gray-100 flex justify-center bg-gray-100 font-sans overflow-hidden">
    <div class="w-full lg:w-5/6">
      <div class="flex flex-col w-36 mt-12">
        <a type="button" href= "{{url_for('patient_blueprint.form_create_patient')}}"class="text-white bg-gradient-to-r from-teal-400 via-teal-500 to-teal-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-teal-300 dark:focus:ring-teal-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">New Patient</a>      
      </div>
      <div class="bg-white shadow-md rounded my-6">
        <table class="min-w-max w-full table-auto">
          <thead>
            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
              <th class="py-3 px-6 text-left">Client</th>
              <th class="py-3 px-6 text-center">Status</th>
              <th class="py-3 px-6 text-left">Date of Birth</th>
              <th class="py-3 px-6 text-left">Sex</th>
              <th class="py-3 px-6 text-center">Actions</th>
            </tr>
          </thead>
          {% for patient in patients %}
          <tbody class="text-gray-600 text-sm font-light">
            <tr class="border-b border-gray-200 hover:bg-gray-100">
              <td class="py-3 px-6 text-left">
                <div class="flex items-center">
                  <div class="mr-2">
                    <img class="w-6 h-6 rounded-full" src="https://randomuser.me/api/portraits/men/{{patient.image_id}}.jpg"/>
                  </div>
                  <span>{{patient.firstname}} {{patient.lastname}}</span>
                </div>
              </td>
              <td class="py-3 px-6 text-center">
                <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">{{patient.status}}</span>
              </td>
              <td class="py-3 px-6 text-left">
                <div class="flex items-center">
                  <span>{{patient.date_of_birth}}</span>
                </div>
              </td>
              <td class="py-3 px-6 text-left">
                <div class="flex items-center">
                  <span>{{patient.sex}}</span>
                </div>
              </td>
              <td class="py-3 px-6">
                <div class="justify-center content-center items-center flex flex-row">
                  <div>
                    <a href='{{url_for("patient_blueprint.delete_patient", id=patient.id )}}'>
                      <div class="flex item-center justify-center cursor-pointer">
                        <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                        </div>
                      </div>
                    </a>
                  </div>

                  <div>
                    <a href='{{url_for("patient_blueprint.update_patient", id=patient.id )}}'>
                      <div class="flex item-center justify-center cursor-pointer">
                        <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                          </svg>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>

              </td>
            </tr>
          </tbody>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>